services:
  db:
    image: postgres:15
    restart: always
    container_name: ventas_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 050816
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d  # 👈 Monta los scripts aquí

  backend:
    build:
      context: .
      dockerfile: ventasApp/Dockerfile
    container_name: ventas_backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 050816
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: front/Dockerfile
    container_name: ventas_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  pgdata:
