spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: 050816
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

jwt:
  secret: TuClaveSecretaMuySegura1234567890
  expiration-ms: 3600000 # 1 hora