spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oms
    username: postgres
    password: 050816
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
jwt:
  secret: TuClaveSecretaMuySegura1234567890
  expiration-ms: 3600000 # 1 hora